# backend/app/models/transaction.py
"""
Transaction and payment-related database models
"""

from sqlalchemy import Column, Integer, String, DateTime, Numeric, ForeignKey, Boolean, Text, JSON, text
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base
from datetime import datetime
from sqlalchemy.dialects.postgresql import UUID, JSONB
import uuid

from app.database import Base


class Transaction(Base):
    """Core transaction model for payment processing"""
    __tablename__ = "transactions"
    
    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False)
    
    # Transaction details
    amount = Column(Numeric(10, 2), nullable=False)
    currency = Column(String(3), nullable=False)
    status = Column(String(20), nullable=False)  # pending, completed, failed, refunded
    transaction_type = Column(String(20), nullable=False)  # payment, refund, payout
    
    # External service references
    stripe_payment_id = Column(String(100), nullable=True)
    shopify_order_id = Column(String(100), nullable=True)
    quickbooks_ref = Column(String(100), nullable=True)
    
    # Metadata
    description = Column(String, nullable=True)
    transaction_metadata = Column(JSONB, nullable=True)
    
    # Timestamps
    created_at = Column(DateTime(timezone=True), default=datetime.utcnow)
    updated_at = Column(DateTime(timezone=True), default=datetime.utcnow, onupdate=datetime.utcnow)
    processed_at = Column(DateTime, nullable=True)
    
    # Relationships
    user = relationship("User", back_populates="transactions")
    insights = relationship("TransactionInsight", back_populates="transaction")


class PaymentMethod(Base):
    """User payment methods"""
    __tablename__ = "payment_methods"
    
    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False)
    
    # Payment method details
    provider = Column(String(50), nullable=False)  # stripe, paypal, etc
    provider_id = Column(String(100), nullable=False)
    method_type = Column(String(20), nullable=False)  # card, bank_account, wallet
    
    # Card/Account info (encrypted)
    last_four = Column(String(4), nullable=True)
    brand = Column(String(20), nullable=True)
    exp_month = Column(Integer, nullable=True)
    exp_year = Column(Integer, nullable=True)
    
    # Status
    is_active = Column(Boolean, default=True)
    is_default = Column(Boolean, default=False)
    
    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    user = relationship("User", back_populates="payment_methods")


class TransactionInsight(Base):
    """AI-generated insights for transactions"""
    __tablename__ = "transaction_insights"
    
    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    transaction_id = Column(String, ForeignKey("transactions.id"), nullable=False)
    
    # Insight data
    insight_type = Column(String(50), nullable=False)  # risk_assessment, trend_analysis, etc
    confidence_score = Column(Numeric(3, 2), nullable=True)
    insight_data = Column(JSON, nullable=False)
    
    # Generated by AI
    ai_model_version = Column(String(50), nullable=False)
    generated_at = Column(DateTime, default=datetime.utcnow)
    
    # Relationships
    transaction = relationship("Transaction", back_populates="insights")